#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { createHmac, randomUUID } from 'node:crypto';
import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = dirname(fileURLToPath(import.meta.url));
const arg = (k, d) => { const i = process.argv.indexOf(k); return i < 0 ? d : process.argv[i + 1]; };
const run = arg('--run');
if (!/^[a-z0-9][a-z0-9-]{0,39}$/.test(run || '')) throw Error('--run is required');
const minutes = Number(arg('--minutes', '30'));
const warmup = Number(arg('--warmup-minutes', '5'));
if (!(minutes > 0 && warmup >= 0)) throw Error('invalid duration');
const env = JSON.parse(readFileSync(join(root, '.abp', run, 'env.json')));
const keys = JSON.parse(readFileSync(join(root, '.abp', run, 'keys.json')));
const own = id => execFileSync('docker', ['inspect', '-f', '{{index .Config.Labels "ai.saycode.abp-run"}}', id], { encoding: 'utf8' }).trim() === run;
for (const id of [env.containers.runtime, env.containers.browserA, env.containers.browserB]) if (!own(id)) throw Error('run ownership mismatch');
const canonical = v => v === null || typeof v !== 'object' ? JSON.stringify(v) : Array.isArray(v) ? `[${v.map(canonical).join(',')}]` : `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
const now = Date.now();
const grant = { kind: 'agent-grant', grantId: `soak-${randomUUID()}`, principalId: 'principal-a', workspaceId: 'workspace-poc', machineId: 'machine-poc', agentSessionId: `soak-${randomUUID()}`, profileId: 'profile-a', allowedOrigins: ['http://a.poc-one.test:8080'], operations: ['createSpace','createTask','openPage','closePage','observe','submitBatch','finishTask','getTask','cancel'], taskSpaceIds: [], issuedAtMs: now, expiresAtMs: now + 30 * 60_000 };
const token = () => { const issuedAtMs = Date.now() - 5000; const fresh = { ...grant, issuedAtMs, expiresAtMs: issuedAtMs + 30 * 60_000 }; const body = Buffer.from(canonical(fresh)).toString('base64url'); return `abp1.${body}.${createHmac('sha256', keys.agentKey).update(`abp1.${body}`).digest('base64url')}`; };
const op = async (name, data) => { const r = await fetch(`http://127.0.0.1:${env.ports.runtime}/v1/ops/${name}`, { method: 'POST', headers: { authorization: `Bearer ${token()}`, 'content-type': 'application/json' }, body: JSON.stringify(data) }); const x = await r.json(); if (!x.ok) throw Error(`${name}: ${x.error?.code}`); return x.result; };
const admin = async () => { const r = await fetch(`http://127.0.0.1:${env.ports.admin}/admin/debug`, { headers: { authorization: `Bearer ${keys.adminToken}` } }); const x = await r.json(); if (!x.ok) throw Error('admin debug failed'); return x.result; };
const docker = (...a) => execFileSync('docker', a, { encoding: 'utf8' }).trim();
const stats = id => JSON.parse(docker('stats', '--no-stream', '--format', 'json', id));
const targets = id => JSON.parse(docker('exec', id, 'python3', '-c', "import urllib.request;print(urllib.request.urlopen('http://127.0.0.1:9222/json/list').read().decode())")).filter(t => t.type === 'page').length;
const journalBytes = () => Number(docker('exec', env.containers.runtime, 'sh', '-c', "du -sb /var/lib/abp | cut -f1"));
const median = xs => { const a = xs.toSorted((x,y) => x-y); return a.length ? (a[Math.floor((a.length-1)/2)] + a[Math.floor(a.length/2)])/2 : NaN; };
const rss = s => { const m = String(s.MemUsage).split('/')[0].trim().match(/^([\d.]+)([KMG]i?B)$/); return m ? Number(m[1]) * ({ KiB: 1024, MiB: 2**20, GiB: 2**30, KB: 1000, MB: 1e6, GB: 1e9 }[m[2]] ?? 1) : NaN; };
const file = join(root, '.abp', run, 'soak.jsonl');
const space = await op('createSpace', { profileId: 'profile-a', requestId: randomUUID() });
const samples = []; let completed = 0, crashes = 0, taskLoss = 0; const start = Date.now();
for (let minute = 0; minute < warmup + minutes; minute++) {
  const task = await op('createTask', { taskSpaceId: space.taskSpaceId, requestId: randomUUID() });
  const opened = await op('openPage', { taskId: task.taskId, url: 'http://a.poc-one.test:8080/marker?label=soak', requestId: randomUUID() });
  const observed = await op('observe', { taskId: task.taskId, tabId: opened.tabId });
  if (!observed.url.includes('/marker')) throw Error('observation target mismatch');
  const finished = await op('finishTask', { taskId: task.taskId, expectedVersion: opened.task.stateVersion, requestId: randomUUID() });
  if (finished.status !== 'succeeded') throw Error('task not succeeded');
  await op('closePage', { taskSpaceId: space.taskSpaceId, tabId: opened.tabId, requestId: randomUUID() });
  const retained = await op('getTask', { taskId: task.taskId }); if (retained.status !== 'succeeded') taskLoss++;
  completed++;
  const debug = await admin();
  const containers = Object.fromEntries(Object.entries(env.containers).filter(([k]) => ['runtime','browserA','browserB'].includes(k)).map(([k,v]) => [k, stats(v)]));
  for (const id of [env.containers.runtime, env.containers.browserA, env.containers.browserB]) if (docker('inspect', '-f', '{{.State.OOMKilled}} {{.State.Running}}', id) !== 'false true') crashes++;
  const sample = { minute, atMs: Date.now(), phase: minute < warmup ? 'warmup' : 'measure', completed, containers, driver: debug.drivers, browserPageTargets: { a: targets(env.containers.browserA), b: targets(env.containers.browserB) }, journalBytes: journalBytes(), heartbeat: { taskId: task.taskId, stateVersion: retained.stateVersion, updatedAtMs: retained.updatedAtMs }, limits: Object.fromEntries(Object.entries(env.containers).filter(([k]) => ['runtime','browserA','browserB'].includes(k)).map(([k,v]) => [k, docker('inspect','-f','{{.HostConfig.Memory}} {{.HostConfig.NanoCpus}}',v)])) };
  appendFileSync(file, JSON.stringify(sample)+'\n'); samples.push(sample);
  const next = start + (minute+1)*60_000; if (next > Date.now()) await new Promise(r => setTimeout(r, next-Date.now()));
}
const measured = samples.filter(s => s.phase === 'measure');
const result = Object.fromEntries(['runtime','browserA','browserB'].map(k => { const first = median(measured.slice(0,5).map(s => rss(s.containers[k]))); const last = median(measured.slice(-5).map(s => rss(s.containers[k]))); return [k, { firstMedianBytes:first, lastMedianBytes:last, allowanceBytes:Math.max(first*.2,100*2**20), pass: measured.length >= 5 && last-first <= Math.max(first*.2,100*2**20) }]; }));
const registryStable = measured.every(s => Object.values(s.driver).every(d => d.counts.tabs === 0 && d.counts.sessions === 0)) && measured.every(s => s.browserPageTargets.a === measured[0].browserPageTargets.a && s.browserPageTargets.b === measured[0].browserPageTargets.b);
const summary = { run, minutes, warmup, completed, crashes, taskLoss, registryStable, result, pass: crashes===0 && taskLoss===0 && registryStable && Object.values(result).every(v=>v.pass) };
writeFileSync(join(root,'.abp',run,'soak-summary.json'), JSON.stringify(summary,null,2)); console.log(JSON.stringify(summary)); if (!summary.pass) process.exitCode=1;
